name: Get CDI/FDI versions from files
description: Get CDI/FDI versions from files
author: Supertokens

# # Add your action's branding here. This will appear on the GitHub Marketplace.
# branding:
#   icon: heart
#   color: red

inputs:
  has-cdi:
    description: Whether the repository contains a coreDriverInterface file
    required: true
    default: true

  has-fdi:
    description: Whether the repository contains a frontendDriverInterface file
    required: true
    default: true

outputs:
  cdi-versions:
    description: List of CDI versions
  
  fdi-versions:
    description: List of FDI versions

runs:
  using: node20
  main: dist/index.js
